In [4]:
from utils.peuler import problem

from functools import cache

import numpy as np

In [54]:
problem(1)

In [55]:
def sol(N):
    return sum([x for x in range(N) if x % 3 == 0 or x % 5 == 0])

In [56]:
sol(10)

23

In [57]:
sol(1000)

233168

In [58]:
problem(2)

In [59]:
@cache
def fibo(n):
    if n == 1:
        return 1
    if n == 2:
        return 2
    return fibo(n-1) + fibo(n-2)

In [60]:
def sol(N):
    last = 1
    i = 2
    sum = 0
    while last <= N:
        last = fibo(i)
        sum += (last % 2 == 0) * last
        i += 1
    return sum

In [61]:
sol(4_000_000)

4613732

In [62]:
problem(3)

In [1]:
from utils.primes import factors

In [2]:
factors(13195)

array([[ 5,  1],
       [ 7,  1],
       [13,  1],
       [29,  1]], dtype=int64)

In [ ]:
factors(600851475143)

array([[  71,    1],
       [ 839,    1],
       [1471,    1],
       [6857,    1]], dtype=int64)

In [ ]:
def sol(N):
    return factors(N).max()

In [ ]:
sol(600851475143)

6857

In [ ]:
problem(4)

In [ ]:
from utils.digits import digits2arr

In [ ]:
def is_palindrome_arr(N):
    if len(N) <= 1:
        return True
    if N[0] != N[-1]:
        return False
    else:
        return is_palindrome_arr(N[1:-1])

In [ ]:
print(is_palindrome_arr([9, 0, 0, 9]))
print(is_palindrome_arr([1, 2, 3]))

True
False


In [ ]:
def is_palindrome(N):
    N = digits2arr(N)
    return is_palindrome_arr(N)

In [ ]:
print(is_palindrome(9009))
print(is_palindrome(123))

True
False


In [ ]:
def sol(N):
    mult = np.fromfunction(lambda i, j: i * j, (10**N, 10**N), dtype='i8')
    return mult[np.vectorize(is_palindrome)(mult)].max()

In [ ]:
sol(2)

9009

In [ ]:
sol(3)

906609

In [ ]:
problem(5)

In [ ]:
from utils.primes import primes, pwrfactors

In [ ]:
mxpwrfactor = lambda p, c: np.clip(np.vectorize(lambda p: pwrfactors(c, p).max(), excluded=['c'])(p), 1, None)

def sol(N):
    p = primes[primes <= N]
    c = np.setdiff1d(np.arange(2, N+1), p)
    pf = mxpwrfactor(p, c)
    return np.prod(p ** pf)

In [ ]:
sol(10)

2520

In [ ]:
sol(20)

232792560

In [ ]:
problem(6)

In [ ]:
def sol(N):
    return np.sum(np.arange(1, N+1)) ** 2 - np.sum(np.arange(1, N+1) ** 2)

In [ ]:
print(sol(10))
print(sol(100))

2640
25164150


$$ 2 \times \sum A^{2}_{N}(\{a, b, \dots,\}) $$

In [ ]:
def combs(l):
    if len(l) < 2:
        return 0
    if len(l) == 2:
        return 2 * l[0] * l[1]
    return 2 * l[-1] * sum(l[:-1]) + combs(l[:-1])

In [ ]:
print(combs(range(10 + 1)))
print(combs(range(100 + 1)))

2640
25164150


In [ ]:
problem(7)

In [ ]:
from utils.primes import primes

In [ ]:
print(primes[6 - 1])
print(primes[10001 - 1])

13
104743


In [ ]:
problem(8)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
import math
np.set_printoptions(linewidth=102)
DIGIT = 73167176531330624919225119674426574742355349194934_96983520312774506326239578318016984801869478851843_85861560789112949495459501737958331952853208805511_12540698747158523863050715693290963295227443043557_66896648950445244523161731856403098711121722383113_62229893423380308135336276614282806444486645238749_30358907296290491560440772390713810515859307960866_70172427121883998797908792274921901699720888093776_65727333001053367881220235421809751254540594752243_52584907711670556013604839586446706324415722155397_53697817977846174064955149290862569321978468622482_83972241375657056057490261407972968652414535100474_82166370484403199890008895243450658541227588666881_16427171479924442928230863465674813919123162824586_17866458359124566529476545682848912883142607690042_24219022671055626321111109370544217506941658960408_07198403850962455444362981230987879927244284909188_84580156166097919133875499200524063689912560717606_05886116467109405077541002256983155200055935729725_71636269561882670428252483600823257530420752963450
print(digits2arr(DIGIT))

[7 3 1 6 7 1 7 6 5 3 1 3 3 0 6 2 4 9 1 9 2 2 5 1 1 9 6 7 4 4 2 6 5 7 4 7 4 2 3 5 5 3 4 9 1 9 4 9 3 4
 9 6 9 8 3 5 2 0 3 1 2 7 7 4 5 0 6 3 2 6 2 3 9 5 7 8 3 1 8 0 1 6 9 8 4 8 0 1 8 6 9 4 7 8 8 5 1 8 4 3
 8 5 8 6 1 5 6 0 7 8 9 1 1 2 9 4 9 4 9 5 4 5 9 5 0 1 7 3 7 9 5 8 3 3 1 9 5 2 8 5 3 2 0 8 8 0 5 5 1 1
 1 2 5 4 0 6 9 8 7 4 7 1 5 8 5 2 3 8 6 3 0 5 0 7 1 5 6 9 3 2 9 0 9 6 3 2 9 5 2 2 7 4 4 3 0 4 3 5 5 7
 6 6 8 9 6 6 4 8 9 5 0 4 4 5 2 4 4 5 2 3 1 6 1 7 3 1 8 5 6 4 0 3 0 9 8 7 1 1 1 2 1 7 2 2 3 8 3 1 1 3
 6 2 2 2 9 8 9 3 4 2 3 3 8 0 3 0 8 1 3 5 3 3 6 2 7 6 6 1 4 2 8 2 8 0 6 4 4 4 4 8 6 6 4 5 2 3 8 7 4 9
 3 0 3 5 8 9 0 7 2 9 6 2 9 0 4 9 1 5 6 0 4 4 0 7 7 2 3 9 0 7 1 3 8 1 0 5 1 5 8 5 9 3 0 7 9 6 0 8 6 6
 7 0 1 7 2 4 2 7 1 2 1 8 8 3 9 9 8 7 9 7 9 0 8 7 9 2 2 7 4 9 2 1 9 0 1 6 9 9 7 2 0 8 8 8 0 9 3 7 7 6
 6 5 7 2 7 3 3 3 0 0 1 0 5 3 3 6 7 8 8 1 2 2 0 2 3 5 4 2 1 8 0 9 7 5 1 2 5 4 5 4 0 5 9 4 7 5 2 2 4 3
 5 2 5 8 4 9 0 7 7 1 1 6 7 0 5 5 6 0 1 3 6 0 4 8 3 9 5 8 6 4 4 6 7 0 6 3 2 4 4 1 5 7 2 2 1 

In [ ]:
def sol(N):
    return np.prod(sliding_window_view(digits2arr(DIGIT), N), axis=1).max()

In [ ]:
print(sol(4))
print(sol(13))

5832
2091059712


In [ ]:
problem(9)

In [ ]:
for a in range(333):
    for b in range(500):
        if a ** 2 + b ** 2 == (1000 - a - b) ** 2:
            c = 1000 - a - b
            print(f"a = {a}, b = {b}, c = {c}")
            print(f"abc = {a * b * c}")

a = 200, b = 375, c = 425
abc = 31875000


In [ ]:
problem(10)

In [ ]:
np.sum(primes[primes < 2e6])

142913828922

In [ ]:
problem(11)

In [ ]:
from io import StringIO

grid = """
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
"""

grid = np.loadtxt(StringIO(grid), dtype='i8')

In [ ]:
m = sliding_window_view(grid, (4, 4))[0,0]
m

array([[ 8,  2, 22, 97],
       [49, 49, 99, 40],
       [81, 49, 31, 73],
       [52, 70, 95, 23]], dtype=int64)

In [ ]:
max4x4 = lambda m: np.max(
                        (
                            np.prod(m.diagonal()), # first diagonal
                            np.prod(np.diagonal(np.rot90(m))), # opposite diagonal
                            np.prod(m, axis=0).max(), # columns
                            np.prod(m, axis=1).max() # lines
                        )
                    )

In [ ]:
np.array([
    max4x4(m)
    for m in sliding_window_view(grid, (4, 4)).reshape((-1, 4, 4))
    ]).max()

70600674

In [ ]:
problem(12)

In [ ]:
trinum = lambda n: np.sum(np.arange(n+1, dtype='uint64'))
print(trinum(7))
print([trinum(x) for x in range(1, 11)])

28
[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


In [ ]:
from itertools import chain, combinations
from math import prod

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [ ]:
divisors = lambda n: np.unique([ np.prod(s) for s in powerset([ item for sublist in [ [e] * p for e, p in factors(n) ] for item in sublist ])]).astype('int')

In [ ]:
for i in range(2, 8):
    t = trinum(i)
    print(f"{i}: {str(divisors(t))}")

2: [1 3]
3: [1 2 3 6]
4: [ 1  2  5 10]
5: [ 1  3  5 15]
6: [ 1  3  7 21]
7: [ 1  2  4  7 14 28]


In [ ]:
divisor_cnt = lambda n : np.prod(factors(n)[:,1] + 1)

In [ ]:
i = 2

while divisor_cnt(trinum(i)) < 200:
    i += 1
    if i % 100 == 0:
        print(f"\r{i}...", end="")

print(f"\r[{i}] {trinum(i)}: divisor_cnt({trinum(i)}) = {divisor_cnt(trinum(i))}")

[2015] 2031120: divisor_cnt(2031120) = 240


In [ ]:
from numba.core.errors import NumbaDeprecationWarning, NumbaPendingDeprecationWarning
import warnings

warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaPendingDeprecationWarning)

In [ ]:
from numba import jit
import numpy as np

primes = np.load('utils/primes_1M.npz')['primes']

@jit
def pwrfactor(N, f):
    n = 1
    while N % f**n == 0:
        n += 1
    return n-1

@jit
def pwrfactors(N, F):
    return np.array([ pwrfactor(N, f) for f in F ])

@jit
def factors(n):
    p = primes[primes <= n]
    f = np.column_stack((p, pwrfactors(n, p).flatten()))
    return f[f[:,1] > 0]

@jit
def trinum(n):
    return np.sum(np.arange(n+1))

@jit
def divisor_cnt(n):
    return np.prod(factors(n)[:,1] + 1)

@jit
def sol(i=2, N=5):
    while divisor_cnt(trinum(i)) < N:
        i += 1
    return i

In [ ]:
i = sol(N=200)
i, trinum(i)

(2015, 2031120)

In [65]:
problem(13)

In [5]:
input = """
37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690
"""

numbers = [int(n) for n in input.strip().split('\n')]

str(sum(numbers))[:10]

'5537376230'

In [7]:
problem(14)

In [13]:
from numba import njit

@njit
def collatz(n):
    return (n % 2) * (3*n + 1) + ((n+1) % 2) * (n / 2)

@njit
def collatz_chain_len(n):
    r = collatz(n)
    cnt = 2
    while r > 1:
        r = collatz(r)
        cnt += 1
    return cnt

In [26]:
chains = np.fromfunction(np.vectorize(collatz_chain_len), (1_000_000,), dtype='uint64')
chains.max(), chains.argmax()

(525, 837799)

In [27]:
problem(15)

In [49]:
# A - B - C
# |   |   |
# D - E - F
# |   |   |
# G - H - I

M = np.array([
    # A  B  C  D  E  F  G  H  I
    [ 0, 1, 0, 1, 0, 0, 0, 0, 0 ], # A
    [ 0, 0, 1, 0, 1, 0, 0, 0, 0 ], # B
    [ 0, 0, 0, 0, 0, 1, 0, 0, 0 ], # C
    [ 0, 0, 0, 0, 1, 0, 1, 0, 0 ], # D
    [ 0, 0, 0, 0, 0, 1, 0, 1, 0 ], # E
    [ 0, 0, 0, 0, 0, 0, 0, 0, 1 ], # F
    [ 0, 0, 0, 0, 0, 0, 0, 1, 0 ], # G
    [ 0, 0, 0, 0, 0, 0, 0, 0, 1 ], # H
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ], # I
])

M += M.T
M

array([[0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0]])

In [48]:
from numpy.linalg import matrix_power

matrix_power(M, 4)[0, 8]

6

In [177]:
def get_neighbors(pt):
    i, j = pt
    n = np.array([
                        [i - 1, j    ], 
        [i    , j - 1],                 [i    , j + 1],
                        [i + 1, j    ]
    ])

    return n[ (0 <= n[:,0]) & (n[:,0] < 20) & (0 <= n[:,1]) & (n[:,1] < 20) ].tolist()

def is_neighbors(p1, p2):
    return (p1 in get_neighbors(p2)) & (p2 in get_neighbors(p1)) & (p1 != p2)

In [226]:
def nb_paths_m(N):
    N += 1

    coords = np.array([ (i, j) for i in range(N) for j in range(N) ]).tolist()

    M = np.array([
        [ int(is_neighbors(p2, p1)) for p1 in coords ]
        for p2 in coords
    ], dtype='uint64')

    return matrix_power(M, (N-1)*2)[0, -1]

In [200]:
@cache
def nb_paths(i, j):
    if i == 0 or j == 0:
        return 1
    return nb_paths(i-1, j) + nb_paths(i, j-1)     

In [212]:
nb_paths(20, 20)

137846528820

In [2]:
problem(16)

In [29]:
from utils.digits import digits2arr, arr2digits

In [9]:
sum(digits2arr(2**1000))

1366

In [11]:
problem(17)

In [95]:
numbers = {
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
    13: "thirteen",
    14: "fourteen",
    15: "fifteen",
    16: "sixteen",
    17: "seventeen",
    18: "eighteen",
    19: "nineteen",
    20: "twenty",
    30: "thirty",
    40: "forty",
    50: "fifty",
    60: "sixty",
    70: "seventy",
    80: "eighty",
    90: "ninety"
}

def english_1000(n):
    if n == 1000:
        return "one thousand"
    d = digits2arr(n)
    s = ""
    if len(d) >= 3:
        s = f"{numbers[d[-3]]} hundred"
    if arr2digits(d[-2:]) > 0:
        if len(d) >= 3:
            s = f"{s} and"
        if arr2digits(d[-2:]) < 20:
            s = f"{s} {numbers[arr2digits(d[-2:])]}"
        else:
            s = f"{s} {numbers[d[-2] * 10]}"
            if d[-1] > 0:
                s = f"{s} {numbers[d[-1]]}"
    return s.strip()
    

In [99]:
[english_1000(x) for x in range(99, 113)]

['ninety nine',
 'one hundred',
 'one hundred and one',
 'one hundred and two',
 'one hundred and three',
 'one hundred and four',
 'one hundred and five',
 'one hundred and six',
 'one hundred and seven',
 'one hundred and eight',
 'one hundred and nine',
 'one hundred and ten',
 'one hundred and eleven',
 'one hundred and twelve']

In [94]:
sum([
    len(english_1000(x).replace(" ", ""))
    for x in range(1, 1001)
    ])

21124

In [101]:
problem(18)

In [5]:
from __future__ import annotations
from dataclasses import dataclass

@dataclass
class Node:
    value: int
    sum_best_path: int = 0
    lparent: Node = None
    rparent: Node = None
    lchild: Node = None
    rchild: Node = None

    def __add__(self, other):
        return self.value + other
    def __radd__(self, other):
        return self + other

In [6]:
from io import StringIO

data = """
75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
"""

In [7]:
def load_nodes(df):
    prev_nodes = []
    for line in df:
        nodes = [ Node(int(v)) for v in line.strip().split()]
        for i, node in enumerate(nodes):
            if i > 0:
                node.lparent = prev_nodes[i-1]
                prev_nodes[i-1].rchild = node
            if i < len(prev_nodes):
                node.rparent = prev_nodes[i]
                prev_nodes[i].lchild = node
        prev_nodes = nodes
    return prev_nodes

In [4]:
def best_path(node):
    if node is None:
        return []
    if sum(best_path(node.lparent)) > sum(best_path(node.rparent)):
        return best_path(node.lparent) + [node]
    else:
        return best_path(node.rparent) + [node]

def best_path_at(line):
    return max([sum(best_path(node)) for node in line])

In [8]:
from numba import jit

@jit(forceobj=True)
def sum_best_path(node):
    if node is None:
        return 0
    if node.sum_best_path > 0:
        return node.sum_best_path
    node.sum_best_path = max(sum_best_path(node.lparent), sum_best_path(node.rparent)) + node
    return node.sum_best_path

def best_path_at(line):
    return max([sum_best_path(node) for node in line])

In [10]:
df = StringIO(data)
best_path_at(load_nodes(df))

1074

In [14]:
problem(67)

In [11]:
with open("p067_triangle.txt", "r") as df:
    best = best_path_at(load_nodes(df))
print(best)

7273


In [15]:
problem(19)

In [154]:
def days(Y, M):
    if M in [9, 4, 6, 11]:
        return list(range(1, 30 + 1))
    if M == 2:
        if ((Y % 4 == 0) and (not (Y % 100 == 0))) or (Y % 400 == 0):
            return list(range(1, 29 + 1))
        else:
            return list(range(1, 28 + 1))
    return list(range(1, 31 + 1))

l = [
    (D, M, Y)
    for Y in range(1900, 2001)
    for M in range(1, 13)
    for D in days(Y, M)
]

In [159]:
1904 / 4

476.0

In [175]:
sundays = [d for i, d in enumerate(l) if i % 7 == 6]

In [176]:
sundays[-10:]

[(29, 10, 2000),
 (5, 11, 2000),
 (12, 11, 2000),
 (19, 11, 2000),
 (26, 11, 2000),
 (3, 12, 2000),
 (10, 12, 2000),
 (17, 12, 2000),
 (24, 12, 2000),
 (31, 12, 2000)]

In [179]:
first_sundays = [sunday for sunday in sundays if sunday[0] == 1 and sunday[2] > 1900]

In [181]:
len(first_sundays)

171

In [16]:
problem(20)

In [21]:
import math
from utils.digits import digits2arr

sum(digits2arr(math.factorial(100)))

648

In [22]:
problem(21)

In [61]:
import importlib
import utils.primes
importlib.reload(utils.primes)

from utils.primes import divisors, factors

In [31]:
proper_divisors = lambda n: np.delete(divisors(n), divisors(n) == n)

In [83]:
d = lambda n: sum(proper_divisors(n))

is_amicable = lambda a: (a != d(a)) and (d(d(a)) == a)

In [84]:
numbers_10000 = np.arange(2, 10_000)
amicable_numbers_10000 = np.array([is_amicable(i) for i in numbers_10000])

In [85]:
numbers_10000[amicable_numbers_10000]

array([ 220,  284, 1184, 1210, 2620, 2924, 5020, 5564, 6232, 6368])

In [86]:
np.sum(numbers_10000[amicable_numbers_10000])

31626

In [182]:
problem(22)

In [195]:
with open('p022_names.txt', 'r') as f:
    names = f.read()
names = sorted(names.replace('"', '').split(','))

In [207]:
txt2vec = lambda s: [ord(c) - 64 for c in s]
alpha = lambda s: sum(s)

In [210]:
alpha(txt2vec('COLIN'))

53

In [211]:
sum([(i+1) * alpha(txt2vec(name)) for i, name in enumerate(names)])

871198282

In [212]:
problem(23)

In [213]:
from utils.primes import divisors

sum(divisors(28)[:-1])

28

In [228]:
abundant = lambda x: x < sum(divisors(x)[:-1])

abundant_lt_28123 = [x for x in range(12, 28123) if abundant(x)]

In [229]:
from itertools import combinations_with_replacement

abundant_pairs = list(combinations_with_replacement(abundant_lt_28123, 2))

In [249]:
fap = [p for p in abundant_pairs if not ((p[0] >= 28123 / 2) and (p[1] >= 28123 / 2))]
sums_of_two_abundant_pairs = np.unique([sum(p) for p in abundant_pairs if sum(p) <= 28123])
not_sums_of_two_abundant_pairs = [x for x in range(1, 28123) if x not in sums_of_two_abundant_pairs]

In [250]:
sum(not_sums_of_two_abundant_pairs)

4179871

In [251]:
problem(24)

In [283]:
from itertools import permutations
from utils.digits import arr2digits, digits2arr

sorted([arr2digits(np.array(p)) for p in permutations([0, 1, 2])])

[12, 21, 102, 120, 201, 210]

In [284]:
sorted([arr2digits(p) for p in permutations(digits2arr(1234567890))])[999_999]

2783915460

In [285]:
problem(25)

In [286]:
from functools import cache

@cache
def fibo(n):
    if n == 1 or n == 2:
        return 1
    return fibo(n-1) + fibo(n-2)

In [289]:
i = 12
while len(digits2arr(fibo(i))) < 1000:
    i += 1

In [291]:
i, fibo(i)

(4782,
 10700662663827589367649805844573968850836838966321516650132352033753145206046940406218891475824897926578046948881775919574843364666725699595129960304612627480924821861440694330512347744427502737817530875793916661921492591867595539664228371489431130746995034395470019854326097230672901928705264472437261177158218255484911205250132014786129659313817922355596574520395061375514678375432291196021299340482607061753977068470682028954869026661854351245219003694806413574474709117076197669456910700980243934396174741037369125032313655321647736970231677550515951735184605799549194109677783732296657965816465139034881542563101842241902598460880001101862555502454939371136516570394476295847145485234259504285824253060835444354282126110089928637950480068943303097732178348645431132057656598684562886168087186938352973506439862976406600007235629179052070511640776148124918858309459405666883391093509444565763576661516193177537928916615813271596168774879838218204925203484738743847367719345127870292186362

In [5]:
problem(26)

In [22]:
from utils.digits import fraction_decimals

In [38]:
def check_repeat(seq, i):
    return seq[len(seq[i:]):i] == seq[i:]

In [39]:
slst

[1]